Transform: AWS::Serverless-2016-10-31
Resources:
  MyFuntion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      InlineCode: |
        import json
        def handler(event, context):
          return {
            "statusCode": 200,
            "body": json.dumps("hello world!")
            }
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get