AWSTemplateFormatVersion: "2010-09-09"

Description: 'Creates the authentication mechanism used for the entire family of manejo apps.'

Parameters:
  EmailVerificationMessage: 
    Description: 'The confirmation message for a user sign-up'
    Type: String
    MinLength: 20
    MaxLength: 200
    Default: 'Para validar seu acesso ao manejo.culturas use o código: {####}.'

  EmailVerificationSubject:
    Description: 'The subject of a confirmation message for a user sign-up'
    Type: String
    MinLength: 5
    MaxLength: 50
    Default: 'Acesso ao aplicativo de manejo ...'

  EmailMessage:
    Description: 'The message for inviting a user to sign-up'
    Type: String
    MinLength: 20
    MaxLength: 200
    Default: 'Esse é um convite para usar o manejo.culturas. Para acessar, use {username} como usuário e {####} como senha.'

  EmailSubject:
    Description: 'The subject of an invitation message for sign-up'
    Type: String
    MinLength: 5
    MaxLength: 50
    Default: 'Dados para acesso ao aplicativo de manejo ...'

  EmailConfigurationARN:
    Description: 'The ARN that represents the email sender from SES'
    Type: String
    Default: 'arn:aws:ses:<region>:<account-id>:identity/<email>'

  EmailConfigurationFrom:
    Description: 'The email source for every message by from Cognito'
    Type: String
    Default: 'xxx <email>'

  EmailConfigurationReply:
    Description: 'The reply email for every message sent by Cognito'
    Type: String
    Default: '<email>'

Resources:

  ManejoAuthUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: 'ManejoUserPool'
      UsernameConfiguration:
        CaseSensitive: False
      UsernameAttributes:
        - 'email'
      AutoVerifiedAttributes:
        - 'email'
      Schema:
        - Name: 'name'
          AttributeDataType: 'String'
          Required: True
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: 'verified_email'
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
        InviteMessageTemplate:
          EmailMessage: !Ref EmailMessage
          EmailSubject: !Ref EmailSubject
      EmailConfiguration:
        EmailSendingAccount: 'DEVELOPER'
        SourceArn: !Ref EmailConfigurationARN
        From: !Ref EmailConfigurationFrom
        ReplyToEmailAddress: !Ref EmailConfigurationReply
      EmailVerificationMessage: !Ref EmailVerificationMessage
      EmailVerificationSubject: !Ref EmailVerificationSubject
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          TemporaryPasswordValidityDays: 180
          RequireUppercase: False
          RequireSymbols: False
          RequireNumbers: True
          RequireLowercase: False
          MinimumLength: 6
      UserPoolTags: 
        'ApplicationResourceType': 'Authentication'
        'Name': 'ManejoAuthUserPool'
        'Service': 'Cognito UP'

  ManejoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: 'ManejoAppClient'
      UserPoolId: !Ref ManejoAuthUserPool
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - 'openid'
      AllowedOAuthFlows:
        - 'code'
      ExplicitAuthFlows:
        - 'ALLOW_ADMIN_USER_PASSWORD_AUTH'
        - 'ALLOW_CUSTOM_AUTH'
        - 'ALLOW_REFRESH_TOKEN_AUTH'
        - 'ALLOW_USER_PASSWORD_AUTH'
        - 'ALLOW_USER_SRP_AUTH'
      GenerateSecret: True
      SupportedIdentityProviders: 
        - 'COGNITO'
      CallbackURLs:
        - 'http://localhost:8080/login/oauth2/code/cognito'
      DefaultRedirectURI: 'http://localhost:8080/login/oauth2/code/cognito'

  ManejoAuthUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      UserPoolId: !Ref ManejoAuthUserPool
      Domain: 'manejoapp'


Outputs:

  ManejoAuthUserPoolExternalRef:
    Description: 'ID for manejo user pool'
    Value: !Ref ManejoAuthUserPool
    Export:
      Name: 'ManejoAuthUserPoolID'

  ManejoAppClientExternalRef:
    Description: 'ID for manejo.app user pool client'
    Value: !Ref ManejoAppClient
    Export:
      Name: 'ManejoAppClientID'
