Resources:
  CustomerAPI:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Description: The customer API for pet-clinic application
      Name: customer-api
      Tags: 
        - Key: application
          Value: pet-clinic

  CustomerResource:
    Type: AWS::ApiGateway::Resource
    Properties: 
      ParentId: !GetAtt
        - CustomerAPI
        - RootResourceId
      PathPart: customers
      RestApiId: !Ref CustomerAPI

Outputs:
  CustomerAPIID:
    Value: !Ref CustomerAPI
    Export:
      Name: CustomerAPIID
  CustomerResourceID:
    Value: !Ref CustomerResource
    Export:
      Name: CustomerResourceID
