Resources:  
    GETSingleCustomer:
      Type: AWS::ApiGateway::Method
      Properties: 
        RestApiId: !ImportValue CustomerAPIID
        ResourceId: !ImportValue CustomerResourceID
        HttpMethod: GET
        AuthorizationType: NONE
        Integration: 
          Type: MOCK
          RequestTemplates: 
            "application/json": '{"statusCode": 200}'
          IntegrationResponses: 
            - StatusCode: 200
              ResponseTemplates: 
                "application/json": !Sub |
                  '{ "statusCode": 200, "message": "Good, success!"}'
        MethodResponses: 
          - StatusCode: 200
  
