Resources:
  PublishAppMessages:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "PublishInfoMessagesToUsers"
      Subscription:
      - Endpoint: "<YOUR-EMAIL-HERE>"
        Protocol: "email"
      Tags:
        - Key: "name"
          Value: "example"
