Resources:
  CustomerAPI:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Description: The customer API for pet-clinic application
      Name: customer-api
      Tags: 
        - Key: application
          Value: pet-clinic

  CustomerResource:
    Type: AWS::ApiGateway::Resource
    Properties: 
      ParentId: !GetAtt
        - CustomerAPI
        - RootResourceId
      PathPart: customers
      RestApiId: !Ref CustomerAPI

  Methods:
      Type: 'AWS::CloudFormation::Stack'
      Properties:
        TemplateURL: >-
          https://s3.amazonaws.com/gabrielcostasilva-bucket-cloudware-nested-stack/nested-api.yaml
        Parameters:
          CustomerAPIID: !Ref CustomerAPI
          CustomerResourceID: !Ref CustomerResource
